export const DATA = [
    {
        id: 'cat1',
        name: 'Electronics',
        suppliers: [
            {
                id: 1,
                name: 'Samsung',
                phone: '0756567654',
                email: 'someone@gmail.com',
                address: 'Kigali, Rwanda',  
                products: [
                    {
                        id: 'sam1',
                        name: 'Samsung Galaxy S21',
                        description: 'Samsung Galaxy S21 is a new smartphone by Samsung, and Galaxy S21 price is $800, on this page you can find the best and most updated price of Galaxy S21 with detailed specifications and features.',
                        sku: 'S21',
                        category: 'Electronics',
                        buyingPrice: '120000',
                        sellingPrice: '130000',
                        quantity: 10,
                        date: '2021-01-01',
                    },
                    {
                        id: 'sam2',
                        name: 'Samsung Galaxy S20',
                        description: 'Samsung Galaxy S20 is a new smartphone by Samsung, and Galaxy S20 price is $700, on this page you can find the best and most updated price of Galaxy S20 with detailed specifications and features.',
                        sku: 'S20',
                        category: 'Electronics',
                        buyingPrice: '100000',
                        sellingPrice: '110000',
                        quantity: 10,
                        date: '2021-01-01',
                    },
                    {
                        id: 'sam3',
                        name: 'Samsung Galaxy S10',
                        description: 'Samsung Galaxy S10 is a new smartphone by Samsung, and Galaxy S10 price is $600, on this page you can find the best and most updated price of Galaxy S10 with detailed specifications and features.',
                        sku: 'S10',
                        category: 'Electronics',
                        buyingPrice: '80000',
                        sellingPrice: '90000',
                        quantity: 10,
                        date: '2021-01-01',
                    },
                    {
                        id: 'sam4',
                        name: 'Samsung Galaxy S9',
                        description: 'Samsung Galaxy S9 is a new smartphone by Samsung, and Galaxy S9 price is $500, on this page you can find the best and most updated price of Galaxy S9 with detailed specifications and features.',
                        sku: 'S9',
                        category: 'Electronics',
                        buyingPrice: '60000',
                        sellingPrice: '70000',
                        quantity: 10,
                        date: '2021-01-01',
                    },
                    {
                        id: 'sam5',
                        name: 'Samsung Galaxy S8',
                        description: 'Samsung Galaxy S8 is a new smartphone by Samsung, and Galaxy S8 price is $400, on this page you can find the best and most updated price of Galaxy S8 with detailed specifications and features.',
                        sku: 'S8',
                        category: 'Electronics',
                        buyingPrice: '40000',
                        sellingPrice: '50000',
                        quantity: 10,
                        date: '2021-01-01',
                    }
                ]
            },
            {
                id: 2,
                name: 'Apple',
                phone: '0756567654',
                email: 'apple@gmail.com',
                address: 'California, USA',
                products: [
                    {
                        id: 'app1',
                        name: 'Apple iPhone 12',
                        description: 'Apple iPhone 12 is a new smartphone by Apple, and iPhone 12 price is $1000, on this page you can find the best and most updated price of iPhone 12 with detailed specifications and features.',
                        sku: '12',
                        category: 'Electronics',
                        buyingPrice: '130000',
                        sellingPrice: '140000',
                        quantity: 10,
                        date: '2021-01-01',
                    },
                    {
                        id: 'app2',
                        name: 'Apple iPhone 11',
                        description: 'Apple iPhone 11 is a new smartphone by Apple, and iPhone 11 price is $900, on this page you can find the best and most updated price of iPhone 11 with detailed specifications and features.',
                        sku: '11',
                        category: 'Electronics',
                        buyingPrice: '110000',
                        sellingPrice: '120000',
                        quantity: 10,
                        date: '2021-01-01',
                    },
                    {
                        id: 'app3',
                        name: 'Apple iPhone X',
                        description: 'Apple iPhone X is a new smartphone by Apple, and iPhone X price is $800, on this page you can find the best and most updated price of iPhone X with detailed specifications and features.',
                        sku: 'X',
                        category: 'Electronics',
                        buyingPrice: '90000',
                        sellingPrice: '100000',
                        quantity: 10,
                        date: '2021-01-01',
                    },
                    {
                        id: 'app4',
                        name: 'Apple iPhone 8',
                        description: 'Apple iPhone 8 is a new smartphone by Apple, and iPhone 8 price is $700, on this page you can find the best and most updated price of iPhone 8 with detailed specifications and features.',
                        sku: '8',
                        category: 'Electronics',
                        buyingPrice: '70000',
                        sellingPrice: '80000',
                        quantity: 10,
                        date: '2021-01-01',
                    },
                    {
                        id: 'app5',
                        name: 'Apple iPhone 7',
                        description: 'Apple iPhone 7 is a new smartphone by Apple, and iPhone 7 price is $600, on this page you can find the best and most updated price of iPhone 7 with detailed specifications and features.',
                        sku: '7',
                        category: 'Electronics',
                        buyingPrice: '60000',
                        sellingPrice: '70000',
                        quantity: 10,
                        date: '2021-01-01',
                    }
                ]
            },
            {
                id: 3,
                name: 'OnePlus',
                phone: '0756567654',
                email: 'oneplus@gmail.com',
                address: 'Shenzhen, China',
                products: [
                    {
                        id: 'one1',
                        name: 'OnePlus 9',
                        description: 'OnePlus 9 is a new smartphone by OnePlus, and OnePlus 9 price is $800, on this page you can find the best and most updated price of OnePlus 9 with detailed specifications and features.',
                        sku: '9',
                        category: 'Electronics',
                        buyingPrice: '100000',
                        sellingPrice: '110000',
                        quantity: 10,
                        date: '2021-01-01',
                    },
                    {
                        id: 'one2',
                        name: 'OnePlus 8',
                        description: 'OnePlus 8 is a new smartphone by OnePlus, and OnePlus 8 price is $700, on this page you can find the best and most updated price of OnePlus 8 with detailed specifications and features.',
                        sku: '8',
                        category: 'Electronics',
                        buyingPrice: '80000',
                        sellingPrice: '90000',
                        quantity: 10,
                        date: '2021-01-01',
                    },
                    {
                        id: 'one3',
                        name: 'OnePlus 7',
                        description: 'OnePlus 7 is a new smartphone by OnePlus, and OnePlus 7 price is $600, on this page you can find the best and most updated price of OnePlus 7 with detailed specifications and features.',
                        sku: '7',
                        category: 'Electronics',
                        buyingPrice: '60000',
                        sellingPrice: '70000',
                        quantity: 10,
                        date: '2021-01-01',
                    },
                    {
                        id: 'one4',
                        name: 'OnePlus 6',
                        description: 'OnePlus 6 is a new smartphone by OnePlus, and OnePlus 6 price is $500, on this page you can find the best and most updated price of OnePlus 6 with detailed specifications and features.',
                        sku: '6',
                        category: 'Electronics',
                        buyingPrice: '50000',
                        sellingPrice: '60000',
                        quantity: 10,
                        date: '2021-01-01',
                    },
                    {
                        id: 'one5',
                        name: 'OnePlus 5',
                        description: 'OnePlus 5 is a new smartphone by OnePlus, and OnePlus 5 price is $400, on this page you can find the best and most updated price of OnePlus 5 with detailed specifications and features.',
                        sku: '5',
                        category: 'Electronics',
                        buyingPrice: '40000',
                        sellingPrice: '50000',
                        quantity: 10,
                        date: '2021-01-01',
                    }
                ]
            },
            {
                id: 4,
                name: 'Xiaomi',
                phone: '0756567654',
                email: 'xiaomi@gmail.com',
                address: 'Beijing, China',
                products: [
                    {
                        id: 'xia1',
                        name: 'Xiaomi Mi 11',
                        description: 'Xiaomi Mi 11 is a new smartphone by Xiaomi, and Mi 11 price is $800, on this page you can find the best and most updated price of Mi 11 with detailed specifications and features.',
                        sku: '11',
                        category: 'Electronics',
                        buyingPrice: '120000',
                        sellingPrice: '130000',
                        quantity: 10,
                        date: '2021-01-01',
                    },
                    {
                        id: 'xia2',
                        name: 'Xiaomi Mi 10',
                        description: 'Xiaomi Mi 10 is a new smartphone by Xiaomi, and Mi 10 price is $700, on this page you can find the best and most updated price of Mi 10 with detailed specifications and features.',
                        sku: '10',
                        category: 'Electronics',
                        buyingPrice: '100000',
                        sellingPrice: '110000',
                        quantity: 10,
                        date: '2021-01-01',
                    },
                    {
                        id: 'xia3',
                        name: 'Xiaomi Mi 9',
                        description: 'Xiaomi Mi 9 is a new smartphone by Xiaomi, and Mi 9 price is $600, on this page you can find the best and most updated price of Mi 9 with detailed specifications and features.',
                        sku: '9',
                        category: 'Electronics',
                        buyingPrice: '80000',
                        sellingPrice: '90000',
                        quantity: 10,
                        date: '2021-01-01',
                    },
                    {
                        id: 'xia4',
                        name: 'Xiaomi Mi 8',
                        description: 'Xiaomi Mi 8 is a new smartphone by Xiaomi, and Mi 8 price is $500, on this page you can find the best and most updated price of Mi 8 with detailed specifications and features.',
                        sku: '8',
                        category: 'Electronics',
                        buyingPrice: '60000',
                        sellingPrice: '70000',
                        quantity: 10,
                        date: '2021-01-01',
                    },
                    {
                        id: 'xia5',
                        name: 'Xiaomi Mi 7',
                        description: 'Xiaomi Mi 7 is a new smartphone by Xiaomi, and Mi 7 price is $400, on this page you can find the best and most updated price of Mi 7 with detailed specifications and features.',
                        sku: '7',
                        category: 'Electronics',
                        buyingPrice: '40000',
                        sellingPrice: '50000',
                        quantity: 10,
                        date: '2021-01-01',
                    }
                ]
            },
            {
                id: 5,
                name: 'Huawei',
                phone: '0756567654',
                email: 'huawei@gmail.com',
                address: 'Shenzhen, China',
                products: [
                    {
                        id: 'hua1',
                        name: 'Huawei P40',
                        description: 'Huawei P40 is a new smartphone by Huawei, and P40 price is $800, on this page you can find the best and most updated price of P40 with detailed specifications and features.',
                        sku: 'P40',
                        category: 'Electronics',
                        buyingPrice: '120000',
                        sellingPrice: '130000',
                        quantity: 10,
                        date: '2021-01-01',
                    },
                    {
                        id: 'hua2',
                        name: 'Huawei P30',
                        description: 'Huawei P30 is a new smartphone by Huawei, and P30 price is $700, on this page you can find the best and most updated price of P30 with detailed specifications and features.',
                        sku: 'P30',
                        category: 'Electronics',
                        buyingPrice: '100000',
                        sellingPrice: '110000',
                        quantity: 10,
                        date: '2021-01-01',
                    },
                    {
                        id: 'hua3',
                        name: 'Huawei P20',
                        description: 'Huawei P20 is a new smartphone by Huawei, and P20 price is $600, on this page you can find the best and most updated price of P20 with detailed specifications and features.',
                        sku: 'P20',
                        category: 'Electronics',
                        buyingPrice: '80000',
                        sellingPrice: '90000',
                        quantity: 10,
                        date: '2021-01-01',
                    },
                    {
                        id: 'hua4',
                        name: 'Huawei P10',
                        description: 'Huawei P10 is a new smartphone by Huawei, and P10 price is $500, on this page you can find the best and most updated price of P10 with detailed specifications and features.',
                        sku: 'P10',
                        category: 'Electronics',
                        buyingPrice: '60000',
                        sellingPrice: '70000',
                        quantity: 10,
                        date: '2021-01-01',
                    },
                    {
                        id: 'hua5',
                        name: 'Huawei P9',
                        description: 'Huawei P9 is a new smartphone by Huawei, and P9 price is $400, on this page you can find the best and most updated price of P9 with detailed specifications and features.',
                        sku: 'P9',
                        category: 'Electronics',
                        buyingPrice: '40000',
                        sellingPrice: '50000',
                        quantity: 10,
                        date: '2021-01-01',
                    }
                ]
            }

        ],
    },
    {
        id: 'cat2',
        name: 'Furniture',
        suppliers: [
            {
                id: 1,
                name: 'IKEA',
                phone: '123456789',
                email: 'contact@ikea.com',
                address: 'Stockholm, Sweden',
                products: [
                    {
                        id: 'ikea1',
                        name: 'BILLY Bookcase',
                        description: 'The BILLY bookcase is a versatile and adaptable storage solution.',
                        sku: 'BILLY001',
                        category: 'Furniture',
                        buyingPrice: '5000',
                        sellingPrice: '6000',
                        quantity: 50,
                        date: '2021-02-01',
                    },
                    {
                        id: 'ikea2',
                        name: 'MALM Bed Frame',
                        description: 'The MALM bed frame is a sleek and stylish bed frame.',
                        sku: 'MALM002',
                        category: 'Furniture',
                        buyingPrice: '15000',
                        sellingPrice: '17000',
                        quantity: 20,
                        date: '2021-02-01',
                    },
                    {
                        id: 'ikea3',
                        name: 'POÄNG Armchair',
                        description: 'The POÄNG armchair is a comfortable and ergonomic chair.',
                        sku: 'POANG003',
                        category: 'Furniture',
                        buyingPrice: '7000',
                        sellingPrice: '8000',
                        quantity: 30,
                        date: '2021-02-01',
                    },
                    {
                        id: 'ikea4',
                        name: 'LACK Coffee Table',
                        description: 'The LACK coffee table is a simple and functional coffee table.',
                        sku: 'LACK004',
                        category: 'Furniture',
                        buyingPrice: '3000',
                        sellingPrice: '4000',
                        quantity: 40,
                        date: '2021-02-01',
                    },
                    {
                        id: 'ikea5',
                        name: 'HEMNES Dresser',
                        description: 'The HEMNES dresser is a classic and elegant dresser.',
                        sku: 'HEMNES005',
                        category: 'Furniture',
                        buyingPrice: '10000',
                        sellingPrice: '12000',
                        quantity: 25,
                        date: '2021-02-01',
                    }
                ]
            },
            {
                id: 2,
                name: 'Ashley Furniture',
                phone: '123456789',
                email: 'contact@ashley.com',
                address: 'Stockholm, Sweden',
                products: [
                    {
                        id: 'ashley1',
                        name: 'Alenya Sofa',
                        description: 'The Alenya sofa is a stylish and comfortable sofa.',
                        sku: 'ALENYA001',
                        category: 'Furniture',
                        buyingPrice: '20000',
                        sellingPrice: '22000',
                        quantity: 15,
                        date: '2021-02-01',
                    },
                    {
                        id: 'ashley2',
                        name: 'Brashland Bed',
                        description: 'The Brashland bed is a rustic and sturdy bed.',
                        sku: 'BRASH002',
                        category: 'Furniture',
                        buyingPrice: '18000',
                        sellingPrice: '20000',
                        quantity: 10,
                        date: '2021-02-01',
                    },
                    {
                        id: 'ashley3',
                        name: 'Realyn Dresser',
                        description: 'The Realyn dresser is a vintage and elegant dresser.',
                        sku: 'REALYN003',
                        category: 'Furniture',
                        buyingPrice: '12000',
                        sellingPrice: '14000',
                        quantity: 20,
                        date: '2021-02-01',
                    },
                    {
                        id: 'ashley4',
                        name: 'Soletren Loveseat',
                        description: 'The Soletren loveseat is a plush and cozy loveseat.',
                        sku: 'SOLET004',
                        category: 'Furniture',
                        buyingPrice: '15000',
                        sellingPrice: '17000',
                        quantity: 18,
                        date: '2021-02-01',
                    },
                    {
                        id: 'ashley5',
                        name: 'Ballister Dining Table',
                        description: 'The Ballister dining table is a robust and stylish table.',
                        sku: 'BALL005',
                        category: 'Furniture',
                        buyingPrice: '13000',
                        sellingPrice: '15000',
                        quantity: 12,
                        date: '2021-02-01',
                    }
                ]
            },
            {
                id: 3,
                name: 'Herman Miller',
                phone: '123456789',
                email: 'contact@herman.com',
                address: 'Stockholm, Sweden',
                products: [
                    {
                        id: 'hm1',
                        name: 'Aeron Chair',
                        description: 'The Aeron chair is a high-end ergonomic office chair.',
                        sku: 'AERON001',
                        category: 'Furniture',
                        buyingPrice: '40000',
                        sellingPrice: '45000',
                        quantity: 10,
                        date: '2021-02-01',
                    },
                    {
                        id: 'hm2',
                        name: 'Embody Chair',
                        description: 'The Embody chair is an ergonomic chair designed for long hours of sitting comfort.',
                        sku: 'EMBODY002',
                        category: 'Furniture',
                        buyingPrice: '50000',
                        sellingPrice: '55000',
                        quantity: 8,
                        date: '2021-02-01',
                    },
                    {
                        id: 'hm3',
                        name: 'Sayl Chair',
                        description: 'The Sayl chair is a stylish and affordable office chair.',
                        sku: 'SAYL003',
                        category: 'Furniture',
                        buyingPrice: '30000',
                        sellingPrice: '35000',
                        quantity: 15,
                        date: '2021-02-01',
                    },
                    {
                        id: 'hm4',
                        name: 'Eames Lounge Chair',
                        description: 'The Eames Lounge chair is an iconic and luxurious lounge chair.',
                        sku: 'EAMES004',
                        category: 'Furniture',
                        buyingPrice: '70000',
                        sellingPrice: '75000',
                        quantity: 5,
                        date: '2021-02-01',
                    },
                    {
                        id: 'hm5',
                        name: 'Noguchi Table',
                        description: 'The Noguchi table is a sculptural and artistic coffee table.',
                        sku: 'NOGUCHI005',
                        category: 'Furniture',
                        buyingPrice: '60000',
                        sellingPrice: '65000',
                        quantity: 7,
                        date: '2021-02-01',
                    }
                ]
            },
            {
                id: 4,
                name: 'Wayfair',
                phone: '123456789',
                email: 'contact@wayfair.com',
                address: 'Stockholm, Sweden',
                products: [
                    {
                        id: 'way1',
                        name: 'Wayfair Basics Bookcase',
                        description: 'The Wayfair Basics bookcase is a simple and functional storage solution.',
                        sku: 'WAYFAIR001',
                        category: 'Furniture',
                        buyingPrice: '6000',
                        sellingPrice: '7000',
                        quantity: 30,
                        date: '2021-02-01',
                    },
                    {
                        id: 'way2',
                        name: 'Wayfair Sleep Mattress',
                        description: 'The Wayfair Sleep mattress is a comfortable and affordable mattress option.',
                        sku: 'WAYFAIR002',
                        category: 'Furniture',
                        buyingPrice: '10000',
                        sellingPrice: '11000',
                        quantity: 25,
                        date: '2021-02-01',
                    },
                    {
                        id: 'way3',
                        name: 'Andover Mills Recliner',
                        description: 'The Andover Mills recliner is a plush and relaxing recliner chair.',
                        sku: 'ANDOVER003',
                        category: 'Furniture',
                        buyingPrice: '12000',
                        sellingPrice: '13000',
                        quantity: 20,
                        date: '2021-02-01',
                    },
                    {
                        id: 'way4',
                        name: 'Beachcrest Home Coffee Table',
                        description: 'The Beachcrest Home coffee table is a coastal-inspired and stylish coffee table.',
                        sku: 'BEACHCREST004',
                        category: 'Furniture',
                        buyingPrice: '8000',
                        sellingPrice: '9000',
                        quantity: 35,
                        date: '2021-02-01',
                    },
                    {
                        id: 'way5',
                        name: 'Latitude Run Desk',
                        description: 'The Latitude Run desk is a modern and functional desk for home offices.',
                        sku: 'LATITUDERUN005',
                        category: 'Furniture',
                        buyingPrice: '15000',
                        sellingPrice: '16000',
                        quantity: 15,
                        date: '2021-02-01',
                    }
                ]
            },
            {
                id: 5,
                name: 'Rooms To Go',
                phone: '123456789',
                email: 'contact@to.com',
                address: 'Stockholm, Sweden',
                products: [
                    {
                        id: 'rtg1',
                        name: 'Cindy Crawford Sectional',
                        description: 'The Cindy Crawford sectional is a luxurious and comfortable sectional sofa.',
                        sku: 'CINDY001',
                        category: 'Furniture',
                        buyingPrice: '25000',
                        sellingPrice: '27000',
                        quantity: 12,
                        date: '2021-02-01',
                    },
                    {
                        id: 'rtg2',
                        name: 'Eric Church Reclining Sofa',
                        description: 'The Eric Church reclining sofa is a rugged and stylish sofa option.',
                        sku: 'ERIC002',
                        category: 'Furniture',
                        buyingPrice: '22000',
                        sellingPrice: '24000',
                        quantity: 10,
                        date: '2021-02-01',
                    },
                    {
                        id: 'rtg3',
                        name: 'Sofia Vergara Dining Set',
                        description: 'The Sofia Vergara dining set is an elegant and luxurious dining set.',
                        sku: 'SOFIA003',
                        category: 'Furniture',
                        buyingPrice: '18000',
                        sellingPrice: '20000',
                        quantity: 15,
                        date: '2021-02-01',
                    },
                    {
                        id: 'rtg4',
                        name: 'Palm Springs Mattress',
                        description: 'The Palm Springs mattress is a plush and comfortable mattress option.',
                        sku: 'PALM004',
                        category: 'Furniture',
                        buyingPrice: '12000',
                        sellingPrice: '13000',
                        quantity: 20,
                        date: '2021-02-01',
                    },
                    {
                        id: 'rtg5',
                        name: 'Alison Hall Chest',
                        description: 'The Alison Hall chest is an antique-inspired and elegant storage chest.',
                        sku: 'ALISON005',
                        category: 'Furniture',
                        buyingPrice: '14000',
                        sellingPrice: '15000',
                        quantity: 18,
                        date: '2021-02-01',
                    }
                ]
            }
        ],
    },
    {
        id: 'cat3',
        name: 'Footwear',
        suppliers: [
            {
                id: 1,
                name: 'Nike',
                phone: '0756567654',
                email: 'nike@gmail.com',
                address: 'Genewa, Netherland',
                products: [
                    {
                        id: 'nike1',
                        name: 'Nike Air Max 270',
                        description: 'Nike Air Max 270 is a stylish and comfortable running shoe.',
                        sku: 'AIRMAX270',
                        category: 'Footwear',
                        buyingPrice: '6000',
                        sellingPrice: '7000',
                        quantity: 20,
                        date: '2021-03-01',
                    },
                    {
                        id: 'nike2',
                        name: 'Nike React Infinity Run Flyknit',
                        description: 'Nike React Infinity Run Flyknit is a high-mileage running shoe with plush cushioning.',
                        sku: 'REACTINFINITY001',
                        category: 'Footwear',
                        buyingPrice: '7000',
                        sellingPrice: '8000',
                        quantity: 15,
                        date: '2021-03-01',
                    },
                    {
                        id: 'nike3',
                        name: 'Nike ZoomX Vaporfly NEXT% 2',
                        description: 'Nike ZoomX Vaporfly NEXT% 2 is a racing shoe designed for speed and efficiency.',
                        sku: 'VAPORFLY002',
                        category: 'Footwear',
                        buyingPrice: '9000',
                        sellingPrice: '10000',
                        quantity: 10,
                        date: '2021-03-01',
                    },
                    {
                        id: 'nike4',
                        name: 'Nike Air Force 1',
                        description: 'Nike Air Force 1 is a classic basketball shoe that offers timeless style and comfort.',
                        sku: 'AIRFORCE1003',
                        category: 'Footwear',
                        buyingPrice: '5000',
                        sellingPrice: '6000',
                        quantity: 25,
                        date: '2021-03-01',
                    },
                    {
                        id: 'nike5',
                        name: 'Nike Blazer Mid \'77 Vintage',
                        description: 'Nike Blazer Mid \'77 Vintage is a retro-inspired sneaker with a classic design.',
                        sku: 'BLAZERMID77004',
                        category: 'Footwear',
                        buyingPrice: '4500',
                        sellingPrice: '5500',
                        quantity: 18,
                        date: '2021-03-01',
                    }
                ]
            },
            {
                id: 2,
                name: 'Adidas',
                phone: '0756567654',
                email: 'adidas@gmail.com',
                address: 'Herzogenaurach, Germany',
                products: [
                    {
                        id: 'adi1',
                        name: 'Adidas Ultra Boost 21',
                        description: 'Adidas Ultra Boost 21 is a high-performance running shoe with Boost cushioning.',
                        sku: 'ULTRABOOST21001',
                        category: 'Footwear',
                        buyingPrice: '6500',
                        sellingPrice: '7500',
                        quantity: 22,
                        date: '2021-03-01',
                    },
                    {
                        id: 'adi2',
                        name: 'Adidas Stan Smith',
                        description: 'Adidas Stan Smith is a classic tennis shoe known for its minimalist design and comfort.',
                        sku: 'STANSMITH002',
                        category: 'Footwear',
                        buyingPrice: '4000',
                        sellingPrice: '5000',
                        quantity: 30,
                        date: '2021-03-01',
                    },
                    {
                        id: 'adi3',
                        name: 'Adidas Superstar',
                        description: 'Adidas Superstar is a legendary basketball shoe with a timeless shell-toe design.',
                        sku: 'SUPERSTAR003',
                        category: 'Footwear',
                        buyingPrice: '4500',
                        sellingPrice: '5500',
                        quantity: 25,
                        date: '2021-03-01',
                    },
                    {
                        id: 'adi4',
                        name: 'Adidas NMD R1',
                        description: 'Adidas NMD R1 is a stylish and comfortable lifestyle shoe with Boost cushioning.',
                        sku: 'NMDR1004',
                        category: 'Footwear',
                        buyingPrice: '6000',
                        sellingPrice: '7000',
                        quantity: 20,
                        date: '2021-03-01',
                    },
                    {
                        id: 'adi5',
                        name: 'Adidas Yeezy Boost 350 V2',
                        description: 'Adidas Yeezy Boost 350 V2 is a popular sneaker designed by Kanye West.',
                        sku: 'YEEZYBOOST350V2005',
                        category: 'Footwear',
                        buyingPrice: '8000',
                        sellingPrice: '9000',
                        quantity: 15,
                        date: '2021-03-01',
                    }
                ]
            },
            {
                id: 3,
                name: 'Puma',
                phone: '0756567654',
                email: 'puma@gmail.com',
                address: 'Herzogenaurach, Germany',
                products: [
                    {
                        id: 'puma1',
                        name: 'Puma Future Rider',
                        description: 'Puma Future Rider is a retro-inspired and comfortable lifestyle shoe.',
                        sku: 'FUTURERIDER001',
                        category: 'Footwear',
                        buyingPrice: '4000',
                        sellingPrice: '4500',
                        quantity: 22,
                        date: '2021-03-01',
                    },
                    {
                        id: 'puma2',
                        name: 'Puma RS-X3',
                        description: 'Puma RS-X3 is a modern and chunky lifestyle shoe with retro-inspired design.',
                        sku: 'RSX3002',
                        category: 'Footwear',
                        buyingPrice: '6000',
                        sellingPrice: '6500',
                        quantity: 18,
                        date: '2021-03-01',
                    },
                    {
                        id: 'puma3',
                        name: 'Puma Clyde Hardwood',
                        description: 'Puma Clyde Hardwood is a basketball shoe with a classic design and modern performance features.',
                        sku: 'CLYDEHARDWOOD003',
                        category: 'Footwear',
                        buyingPrice: '5500',
                        sellingPrice: '6500',
                        quantity: 20,
                        date: '2021-03-01',
                    },
                    {
                        id: 'puma4',
                        name: 'Puma Suede Classic',
                        description: 'Puma Suede Classic is a timeless sneaker known for its comfort and versatility.',
                        sku: 'SUEDECLASSIC004',
                        category: 'Footwear',
                        buyingPrice: '3500',
                        sellingPrice: '4000',
                        quantity: 25,
                        date: '2021-03-01',
                    },
                    {
                        id: 'puma5',
                        name: 'Puma King Platinum FG',
                        description: 'Puma King Platinum FG is a soccer cleat known for its lightweight design and excellent traction.',
                        sku: 'KINGPLATINUMFG005',
                        category: 'Footwear',
                        buyingPrice: '7000',
                        sellingPrice: '8000',
                        quantity: 15,
                        date: '2021-03-01',
                    }
                ]
            },
            {
                id: 4,
                name: 'New Balance',
                phone: '0756567654',
                email: 'newbalance@gmail.com',
                address: 'Boston, USA',
                products: [
                    {
                        id: 'nb1',
                        name: 'New Balance Fresh Foam 1080v11',
                        description: 'New Balance Fresh Foam 1080v11 is a cushioned running shoe with a plush feel.',
                        sku: 'FRESHFOAM1080V11001',
                        category: 'Footwear',
                        buyingPrice: '7000',
                        sellingPrice: '8000',
                        quantity: 20,
                        date: '2021-03-01',
                    },
                    {
                        id: 'nb2',
                        name: 'New Balance FuelCell Rebel v2',
                        description: 'New Balance FuelCell Rebel v2 is a lightweight and responsive running shoe.',
                        sku: 'FUELCELLREBELV2002',
                        category: 'Footwear',
                        buyingPrice: '8000',
                        sellingPrice: '9000',
                        quantity: 18,
                        date: '2021-03-01',
                    },
                    {
                        id: 'nb3',
                        name: 'New Balance 574',
                        description: 'New Balance 574 is a classic sneaker known for its retro styling and comfort.',
                        sku: 'NB574003',
                        category: 'Footwear',
                        buyingPrice: '4500',
                        sellingPrice: '5500',
                        quantity: 25,
                        date: '2021-03-01',
                    },
                    {
                        id: 'nb4',
                        name: 'New Balance Fresh Foam Hierro v6',
                        description: 'New Balance Fresh Foam Hierro v6 is a trail running shoe with excellent cushioning and traction.',
                        sku: 'FRESHFOAMHIERROV6004',
                        category: 'Footwear',
                        buyingPrice: '9000',
                        sellingPrice: '10000',
                        quantity: 15,
                        date: '2021-03-01',
                    },
                    {
                        id: 'nb5',
                        name: 'New Balance 990v5',
                        description: 'New Balance 990v5 is a premium sneaker known for its comfort and durability.',
                        sku: 'NB990V5005',
                        category: 'Footwear',
                        buyingPrice: '10000',
                        sellingPrice: '11000',
                        quantity: 12,
                        date: '2021-03-01',
                    }
                ]
            },
            {
                id: 5,
                name: 'Reebok',
                phone: '0756567654',
                email: 'reebok@gmail.com',
                address: 'Boston, USA',
                products: [
                    {
                        id: 'reebok1',
                        name: 'Reebok Nano X1',
                        description: 'Reebok Nano X1 is a versatile training shoe designed for high-intensity workouts.',
                        sku: 'NANOX1001',
                        category: 'Footwear',
                        buyingPrice: '6000',
                        sellingPrice: '7000',
                        quantity: 22,
                        date: '2021-03-01',
                    },
                    {
                        id: 'reebok2',
                        name: 'Reebok Classic Leather',
                        description: 'Reebok Classic Leather is an iconic sneaker known for its timeless design and comfort.',
                        sku: 'CLASSICLEATHER002',
                        category: 'Footwear',
                        buyingPrice: '4500',
                        sellingPrice: '5500',
                        quantity: 25,
                        date: '2021-03-01',
                    },
                    {
                        id: 'reebok3',
                        name: 'Reebok Zig Kinetica',
                        description: 'Reebok Zig Kinetica is a running shoe with a unique and responsive cushioning system.',
                        sku: 'ZIGKINETICA003',
                        category: 'Footwear',
                        buyingPrice: '5000',
                        sellingPrice: '6000',
                        quantity: 20,
                        date: '2021-03-01',
                    },
                    {
                        id: 'reebok4',
                        name: 'Reebok Club C 85',
                        description: 'Reebok Club C 85 is a classic tennis shoe known for its minimalist design and comfort.',
                        sku: 'CLUBC85004',
                        category: 'Footwear',
                        buyingPrice: '4000',
                        sellingPrice: '5000',
                        quantity: 30,
                        date: '2021-03-01',
                    },
                    {
                        id: 'reebok5',
                        name: 'Reebok Floatride Energy 3',
                        description: 'Reebok Floatride Energy 3 is a lightweight and responsive running shoe.',
                        sku: 'FLOATRIDEENERGY3005',
                        category: 'Footwear',
                        buyingPrice: '5500',
                        sellingPrice: '6500',
                        quantity: 18,
                        date: '2021-03-01',
                    }
                ]
            }
        ],
    },
    

];


export const countryList = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "The Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo, Democratic Republic of the",
    "Congo, Republic of the",
    "Costa Rica",
    "Côte d’Ivoire",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "East Timor (Timor-Leste)",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "The Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Korea, North",
    "Korea, South",
    "Kosovo",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia, Federated States of",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar (Burma)",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Sudan, South",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Taiwan",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Vatican City",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe"
];